Console.Clear();
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write("Contando até dez: ");
Console.ForegroundColor = ConsoleColor.Red;
Thread.Sleep(1000);
Console.Write(" 0 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write(" 1 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write(" 2 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write(" 3 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write(" 4 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write(" 5 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write(" 6 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write(" 7 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write(" 8 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write(" 9 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.Write(" 10 ");
Thread.Sleep(1000);
Console.ResetColor();
Console.Write(" 💥");